### PR TITLE
[Feature] Add basic tutorial for SR models

### PR DESCRIPTION
**Pull request by ckkelvinchan**
## Motivation
A demo teaching users how to train and test existing models could help them get familiar with MMEditing.

## Modification
This PR adds a basic tutorial for SR models. It includes both image and video SR models.

## Remarks
There is a link to the comprehensive models, but the link hasn't been added.

### CODE REVIEW

**Comment by ckkelvinchan** [comment]
Please feel free to leave comments :)

**Comment by innerlee** [comment]
See the installation step here https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb
The mmcv-full is generally installed manually

**Comment by ckkelvinchan** [comment]
> See the installation step here https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb
> The mmcv-full is generally installed manually
> 
> edit:
> also add a colab badge as in the above file. Try to run the whole file in colab to make sure it can run there

Note that the cell training and testing on pre-defined datasets are not expected to be run. It is used as a demo showing users how to use the command.

**Comment by ckkelvinchan** [comment]
It has been tested on colab.

**Comment by innerlee** [comment]
The file cannot be displayed by github. Please check if the format is correct.

Rebase master btw :)

**Review by innerlee — APPROVED** [review]

**Pull request merged**
