### PR TITLE
[Fix] use hyphen for command line args in demo & tools 

### PR DESCRIPTION
**Pull request by nijkah**
closes https://github.com/open-mmlab/mmediting/issues/804

### CODE REVIEW

**Comment by Yshuo-Li** [comment]
Good job.

Maybe markdown files such as `docs/en/demo.md`.

**Comment by Yshuo-Li** [comment]
We can find all `--xx_x` by the following command

`grep -rn -E -- '--[[:alnum:]]+_' docs`

**Comment by nijkah** [comment]
> We can find all `--xx_x` by the following command
> 
> `grep -rn -E -- '--[[:alnum:]]+_' docs`

I ran 
```
grep -e "--\w*_" -rn demo/*.py 
grep -e "--\w*_" -rn tools
grep -e "--\w*_" -rn docs
```

and added support to previous arguments.
+ Lint

**Comment by wangruohui** [comment]
@Yshuo-Li 

Would the following implementation be better? We can use only hyphens in `argparse`, and add an additional function to check and modify underscore `_` in-place in `sys.argv`. By doing so, the code would be kept clean.

We can put this function to `mmedit/utils/cli.py` and import them in demo scripts. 


save to `arg.py` and test with the command line.

```python
import warnings
import sys
import re


def parse_args():
    parser = argparse.ArgumentParser(description="Generation demo")
    parser.add_argument("--a-b", help="test config file path")
    parser.add_argument("--c-d-e", help="test config file path")
    parser.add_argument("--f", help="test config file path")
    args = parser.parse_args()
    return args


def main():
    print(sys.argv)
    modify_args()
    print(sys.argv)
    args = parse_args()
    print(args)


def modify_args():
    for i, v in enumerate(sys.argv):
        if i == 0:
            assert v.endswith(".py")
        elif re.match(r"--\w+_.*", v):
            new_arg = v.replace("_", "-")
            warnings.warn(
                f"command line argument {v} is deprecated, please use {new_arg} instead.",
                category=DeprecationWarning,
            )
            sys.argv[i] = new_arg


if __name__ == "__main__":
    main()
```

**Comment by nijkah** [comment]
@wangruohui 
I updated it.
Note that `local_rank` in tools/train.py and tools/test.py is not modified because it is from pytorch's convention.

**Comment by wangruohui** [comment]
@nijkah Thank you very much!

**Review by wangruohui — APPROVED** [review]

**Comment by nijkah** [comment]
Should I add a test code for `modify_args`?

**Review by Yshuo-Li — APPROVED** [review]

**Comment by Yshuo-Li** [comment]
> Should I add a test code for `modify_args`?

Yeah, that will be better.

**Review by Yshuo-Li — APPROVED** [review]

**Pull request merged**
