### PR TITLE
[Fix] Change the path to pre-trained EDVR-M

### PR DESCRIPTION
**Pull request by ckkelvinchan**
## Motivation
As discussed in #391, there are additional `.modules`'s  in `edvrm_x4_8x4_600k_reds_20200622-ba4a43e4.pth`. Therefore, the weights cannot be correctly loaded.

## Modification
We manually removed the unnecessary `.modules`. The path to the modified model is changed.

### CODE REVIEW

**Comment by innerlee** [comment]
Any idea on the cause?

**Comment by ckkelvinchan** [comment]
> Any idea on the cause?

No clue at the moment. It seems not the problem of `publish_model`. I guess `model = model.module` is not execute for some unknown reasons.

**Comment by innerlee** [comment]
Would you mind digging into this problem?

**Comment by ckkelvinchan** [comment]
> Would you mind digging into this problem?

Sure I will try

**Comment by ckkelvinchan** [comment]
I tried training the model and there is no error in this current version. 

I checked the commit history and found that two EDVR-M models are uploaded in the same commit. It is kind of strange that only one has this problem. May need more time but not sure whether I can figure it out.

**Review by innerlee — APPROVED** [review]

**Pull request merged**
