### PR TITLE
[Feature] Add BaseVFIDataset

### PR DESCRIPTION
**Pull request by Yshuo-Li**

### CODE REVIEW

**Review by ckkelvinchan — COMMENTED** [review]
Some lines are not covered by unittests. 

Moreover, please check if a dataset contains multiple videos with different number of frames, how the PSNR is calculated. In video SR, we usually compute the average PSNR of each video, and then take the average of all videos, as shown [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_folder_video_dataset.py#L170).

**Comment by Yshuo-Li** [comment]
> Some lines are not covered by unittests.
> 
> Moreover, please check if a dataset contains multiple videos with different number of frames, how the PSNR is calculated. In video SR, we usually compute the average PSNR of each video, and then take the average of all videos, as shown [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_folder_video_dataset.py#L170).

If a dataset contains multiple videos with different numbers of frames, it should inherit the basic class and modify this function.

**Comment by ckkelvinchan** [comment]
> > Some lines are not covered by unittests.
> > Moreover, please check if a dataset contains multiple videos with different number of frames, how the PSNR is calculated. In video SR, we usually compute the average PSNR of each video, and then take the average of all videos, as shown [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_folder_video_dataset.py#L170).
> 
> If a dataset contains multiple videos with different numbers of frames, it should inherit the basic class and modify this function.

So this dataset is for `N frames -> 1 frame` case?

**Comment by Yshuo-Li** [comment]
> > > Some lines are not covered by unittests.
> > > Moreover, please check if a dataset contains multiple videos with different number of frames, how the PSNR is calculated. In video SR, we usually compute the average PSNR of each video, and then take the average of all videos, as shown [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_folder_video_dataset.py#L170).
> > 
> > 
> > If a dataset contains multiple videos with different numbers of frames, it should inherit the basic class and modify this function.
> 
> So this dataset is for `N frames -> 1 frame` case?

Yes, 2 frames -> 1 frame

**Review by ckkelvinchan — APPROVED** [review]

**Pull request merged**
