### PR TITLE
[enhance] Add custom_hooks

### PR DESCRIPTION
**Pull request by Yshuo-Li**

### CODE REVIEW

**Comment by innerlee** [comment]
Does this affect testing?

**Comment by Yshuo-Li** [comment]
> Does this affect testing?

It doesn't affect testing.

**Review by innerlee — APPROVED** [review]

**Comment by yumath** [comment]
parameters which created in my custom hook can not be updated

**Comment by yumath** [comment]
> parameters which created in my custom hook can not be updated by grad

I replaced the modules in runner.model

**Pull request merged**
