### PR TITLE
Replace string version comparison with `package.version.parse`

### LINKED ISSUE #722: Various pytorch version comparisons return the wrong result with pytorch >= 1.10
Various functions use the string comparison `torch.__version__ > 'x.y'` in order to determine if the current version of pytorch is higher than a certain version. However, this returns an incorrect result when `torch.__version__` is greater or equal than 1.10.

Examples of this issue are [here](https://github.com/open-mmlab/mmediting/blob/master/tools/publish_model.py#L24), [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/builder.py#L145) and [here](https://github.com/open-mmlab/mmediting/blob/master/tests/test_runtime/test_ema_hook.py#L16).

This results, for example, in `persistent_workers` not being set to True when creating a DataLoader in pytorch 1.10.

### PR DESCRIPTION
**Pull request by Juggernaut93**

### CODE REVIEW

**Comment by wangruohui** [comment]
Hi, thank you for your contribution. 
The CI is still running but if the lint fails, you probably need to run `isort` to sort imports to pass the lint. We have some kind of format checking.

**Comment by Juggernaut93** [comment]
I ran isort by using the settings in setup.cfg, the tool changed one import, but I'm not sure if it's now correct. First time I use isort.

**Review by wangruohui — APPROVED** [review]

**Comment by wangruohui** [comment]
The feature is also integrated into some modern editors such as pycharm and vscode. You can also sort them in the editor directly.

**Review by wangruohui — APPROVED** [review]

**Comment by OpenMMLab-Assistant003** [comment]
Hi @Juggernaut93！First of all, we want to express our gratitude for your significant PR in the MMEditing project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @Juggernaut93

**Pull request merged**
