### PR TITLE
modify:

### PR DESCRIPTION
**Pull request by liuky74**
## Motivation

Fix errors in the TTSR configuration file

### CODE REVIEW

**Comment by LeoXing1996** [comment]
Hey @liuky74, thanks for your contribution. Can you provide screenshots of running the original config and your modification ones to verify your modification?

**Comment by liuky74** [comment]
> Hey @liuky74, thanks for your contribution. Can you provide screenshots of running the original config and your modification ones to verify your modification?
of course, there is original config: 
image

after modification:
image

**Comment by liuwenran** [comment]
@LeoXing1996 , this pr comes from this issue [https://github.com/open-mmlab/mmediting/issues/1426](url)

**Comment by OpenMMLab-Miao** [comment]
Dear liuky74,
First of all, we want to express our gratitude for your significant PR in the MMEditing project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.
If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. We look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG
Thank you again for your contribution❤
Best regards！ @liuky74

**Pull request merged**
