### PR TITLE
[Fix] torch.new_tensor will cause device error when pytorch>=1.7

### PR DESCRIPTION
**Pull request by nbei**

### CODE REVIEW

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
Can this be tested (in cpu mode)?

**Comment by nbei** [comment]
> Can this be tested (in cpu mode)?

Sure. The modification is to guarantee that two tensors are in the same device.

**Comment by innerlee** [comment]
Okay then please add a test case for this ;) My understanding is that the current code is only tested on gpu mode, so it will slip through the ci

**Comment by nbei** [comment]
> Okay then please add a test case for this ;) My understanding is that the current code is only tested on gpu mode, so it will slip through the ci

No. Current code has been tested on CPU. It will not report error, because the tensors will be put on CPU by default.

**Comment by innerlee** [comment]
yeah your right

**Pull request merged**
