### PR TITLE
[Fix] Fix output dtype of RandomNoise

### PR DESCRIPTION
**Pull request by dienachtderwelt**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

_apply_poisson_noise() will change image dtype to np.float64. When other RandomNoise exists in degradations it can cause cv2.cvtColor(noise[..., [2, 1, 0]], cv2.COLOR_BGR2GRAY) to collapse.

## Modification

1) Cast dtype of np.random.poisson(noise * unique_val) to np.float32.
2) Add corresponding unit tests.

## Who can help? @ them here!
@liuwenran Thanks for invitation. Here comes my first tech PR 😃

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by dienachtderwelt** [comment]
Sorry this branch is aimed to add new features to random_degradations. But used to fix a bug first. Really should do that in another branch LOL

**Comment by Z-Fran** [comment]
This bug you mentioned is exactly existing. Thanks for your contribution.  Does PairedRandomResize be used in any model or some cases? @dienachtderwelt

**Comment by dienachtderwelt** [comment]
Can refer to this paper in section 3.2 where it talks about resizing as part of the data synthesis pipeline: https://arxiv.org/pdf/2203.13278.pdf
In SR tasks it's natural to have gt and lq with different resolution. But if you want generate synthetic data for denoising models gt and lq have to match. 
Hope this gives you a use case example. @Z-Fran

**Comment by Z-Fran** [comment]
So are you supporting SCUNet based on MMEditing? I think you can create a pull request to commit SCUNet with this PairedRandomResize pipeline together in another PR. And this PR only fixs the bug.

**Comment by dienachtderwelt** [comment]
Actually I’m only using mmediting for training lol
Of course can make this branch only fix the bug @Z-Fran

**Comment by Z-Fran** [comment]
Merging PairedRandomResize in MMEditing when it's used in some models would be better. Now you can just fix this bug.

**Comment by dienachtderwelt** [comment]
Sure. Branch rebased. @Z-Fran

**Review by Z-Fran — APPROVED** [review]

**Pull request merged**
