### PR TITLE
[Fix]: add type and change default number of preprocess_div2k_dataset.py

### PR DESCRIPTION
**Pull request by ruoningYu**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

python tools/dataset_converters/super-resolution/div2k/preprocess_div2k_dataset.py --data-root ./data/DIV2K
image

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by LeoXing1996** [comment]
Hi @ruoningYu , thanks for your contribution. 
This PR looks good to me. Could you please provide a screenshot of the modified program running properly? Then this PR can be merged.

**Comment by ruoningYu** [comment]
When I run this script on dev.1-x, I get the following error:
image
Is the interface changed ?

**Comment by LeoXing1996** [comment]
@ruoningYu Ops, seems you find another bug in dev-1.x. You should change,`mmcv.scandir` to `mmengine.scandir`

**Comment by zengyh1900** [comment]
I have fixed it and tried the script by running: 
`python tools/dataset_converters/super-resolution/div2k/preprocess_div2k_dataset.py --data-root ./data/DIV2K`
image
It works well. I think this pull request can be approved.

**Review by LeoXing1996 — APPROVED** [review]

**Pull request merged**
