### PR TITLE
Tiny fix: fix preprocess_vimeo90k_dataset.py args name

### PR DESCRIPTION
**Pull request by hahnjiang**

### CODE REVIEW

**Comment by innerlee** [comment]
Hi, thanks for the contribution! Argparse should support both "a-b" and "a_b", so, does the original code caused any problems?

**Comment by hahnjiang** [comment]
"a-b" will cause exception.
```
Traceback (most recent call last):
  File "preprocess_vimeo90k_dataset.py", line 154, in <module>
    generate_anno_file(args.train_list)
AttributeError: 'Namespace' object has no attribute 'train_list'
```

**Comment by innerlee** [comment]
What was the shell cmd used?

**Comment by hahnjiang** [comment]
cmd: 
```
python preprocess_vimeo90k_dataset.py .../mmediting/data/sequences  .../mmediting/data/sequences  .../mmediting/data/sep_trainlist.txt  --make-lmdb
```

**Comment by innerlee** [comment]
Thanks! I see. The replacement does not work on positional args.

**Review by innerlee — APPROVED** [review]

**Comment by OpenMMLab-Assistant-007** [comment]
Hi!
@hahnjiang 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
